# Site settings
title: "PiLock User Guide"
description: "Complete documentation for PiLock device configuration and usage"
url: ""
baseurl: ""
author: "Artisan Forge Designs"

# Theme
remote_theme: abhinavs/moonwalk

# Moonwalk theme settings
theme_config:
  appearance: "dark" # can be "light", "dark", or "auto"
  back_home_text: "← Back to Home"
  date_format: "%Y-%m-%d"
  show_description: true
  show_navbar: true
  show_footer: true

# Navigation
navigation:
  - title: "Home"
    url: "/"
  - title: "Documentation"
    url: "/"

# Social links (optional)
social_links:
  - title: "GitHub"
    url: "https://github.com/blenington/afd/afd-web"
    icon: "fab fa-github"

# Moonwalk specific settings
home:
  title: "PiLock"
  description: "Complete device configuration and usage documentation"

# Footer
footer_content: "Copyright &copy; 2025 Artisan Forge Designs."

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# Sass settings
sass:
  sass_dir: _sass
  style: compressed

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE